### ISSUE TITLE
[EPIC] Project Roadmap

### ISSUE THREAD

**Issue by NashJames** [NashJames/Holocron.io#1]
### Iteration 1:

- [x] Initial project configuration
- [x] Add Fetch
- [x] Add CodeMirror
- [x] Add server side fetch for page load performance
- [x] Add SearchBar (Radix-UI design style)
- [x] Add Ascii art easter egg to browser console
- [x] Add Theme (MUI)
- [x] Build app header (Curved rectangle 50% width centre screen at the top. Fixed on scroll. Add external archives and github links)

### Iteration 2:

- [x] Inkscape: Design background (Miniature SVGs to distribute across the page. Lots of single pixel blues like stars made of fibre optic?)
- [x] Inkscape: Design background death star (Geometric styling. Fades out left to right?)
- [x] Inkscape: Simple geometric Holocron logo design. Add spinning animation inside HTML style tag?
- [x] Add paragraph description/explanation under header?
- [x] Add Typography
- [x] Refactor UI Design

### Iteration 3:

- [x] Animations: Translate elements upwards into view on page load
- [x] Add CI checks for linting and prettier
- [x] Write E2E tests - Playwright
- [x] Write Snapshot tests - Jest

Mood Board: [Dribble - Millenium Falcon](https://dribbble.com/shots/12234046-The-Millennium-Falcon), [GitHub Downloads](https://desktop.github.com/), [Father-Son-Daughter Wall Mural](https://i.pinimg.com/originals/ee/d2/34/eed234e3ef511be7c4838630d93a3a86.jpg), Jedi Temple, [Death Star illustration](https://st3.depositphotos.com/4187959/14647/v/600/depositphotos_146470655-stock-illustration-star-station-space-illustration.jpg)

### Iteration 1:

- [x] Add api response time box to CodeMirror
- [x] Add copy URL button to top-right of CodeMirror. Show url in tooltip 
- [x] Add loading spinner to CodeMirror
- [x] Animations: Meteors on CodeMirror background
- [x] Mobile Responsiveness ([Responsively App](https://github.com/responsively-org/responsively-app))
- [x] Adjust folder structure and tests for a production environment
- [ ] Add security headers (Delayed - Waiting on [Next.js CSP middleware fixes](https://github.com/vercel/next.js/discussions/54907))

### Iteration 2:

- [ ] Add basic POST API. Use JSON schema for types as it's language agnostic.
- [ ] Meilisearch API data with autocomplete ([Demo w/ recent searches and categories](https://codesandbox.io/s/github/algolia/autocomplete/tree/next/examples/query-suggestions-with-recent-searches-and-categories?file=/app.tsx)). Can it search the entire dataset and clicking on the item will prefill the relevant API link to the search bar? E.g. Search 'Luke Skywalker' will return 'https://swapi.dev/api/people/1/'
- [ ] Searching should add to the URL. Possibly under `/search/[subject]/[id]`, with autoscrolling the user down to the CodeMirror
- [ ] Add rate-limiting
- [ ] Add basic metrics for requests
- [ ] Add docs page (about the data, basic API interaction, language-specific interactions) - docasaurus/gitbook, meilisearch and giscus?
- [ ] Add app footer info (API license, disney copyright, etc. Credit original authors/hosts? List technologies? Designed & built by...) - docs only?
- [ ] Update readme (Badges [code license, api license, code climate, test coverage, CI status, etc.], [all-contributors](https://github.com/all-contributors/all-contributors)) - carbon?
- [ ] Add repo social preview image (Adjust banner to include 40pt border)

### Iteration 3:

- [ ] Add graphql interactions
- [ ] Update docs (graphql Interactions)
- [ ] Add settings pop-out sidebar (like mui docs). Options for dark/light mode (not full white? cream?), accent colour theme (mimic lightsaber colour options?), font size, colour blindness, language?. Have the allow or deny cookies option at bottom with helper text: "To remember these options, enable cookies below".
- [ ] Add notifications like MUI docs? To announce additional API interactions, etc.
- [ ] Animation: Hovering on Death Star builds it by translating other SVGs (e.g. moving the pieces from Andor S1 ending into place, then activating it)
- [ ] Add [screenshot testing](https://playwright.dev/docs/screenshots) with visual regression tests
- [ ] Create contributing + development guide for repo
- [ ] Custom 404 and 500 error pages
- [ ] Add SEO
- [ ] Deploy to custom site?

## Building a stronger API service

- [ ] Create DB with data
- [ ] Create a rust server for requests - [rtz crate](https://www.reddit.com/r/rust/comments/156sxbs/rtz_an_extremely_fast_timezone_resolution_library/)
- [ ] Create docker image of DB and rust server ([Fly.io](https://fly.io/))
- [ ] Update docs (Docker Image Interaction, How to create an API)
- [ ] Add a statistics page. Usage Graphs, Benchmark Tests (GraphQL vs REST), etc.
- [ ] ThreeJS world map (live pings when someone makes a request)

## Expanding the dataset

- [ ] Crawl data from https://starwars.fandom.com/wiki/Millenium_Falcon?action=edit or page HTML. Data licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
- [ ] Include images and low quality/short videos for real-world testing applications
- [ ] Additional API languages: https://starwars.fandom.com/wiki/List_of_Star_Wars_Wikis_in_other_languages
- [ ] Additional UI languages - Written German is roughly 45% longer than English. Test any broken UI layouts
- [ ] Add UI language choice to settings sidebar (incl. Aurebesh and Wookie?). Detect language by  `window.navigator.language`
